from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Tag',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),('name',models.CharField(max_length=50,unique=True)),('color',models.CharField(default='#3498db',max_length=7))],options={'ordering':['name']}),
        migrations.CreateModel(name='Task',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),('title',models.CharField(max_length=200)),('description',models.TextField()),('status',models.CharField(choices=[('pending','Pending'),('in_progress','In Progress'),('completed','Completed'),('on_hold','On Hold')],default='pending',max_length=20)),('priority',models.CharField(choices=[('low','Low'),('medium','Medium'),('high','High'),('critical','Critical')],default='medium',max_length=20)),('deadline',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('attachment',models.FileField(blank=True,null=True,upload_to='task_attachments/')),('completion_note',models.TextField(blank=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_tasks',to=settings.AUTH_USER_MODEL)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='created_tasks',to=settings.AUTH_USER_MODEL)),('tags',models.ManyToManyField(blank=True,to='tasks.Tag'))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='Comment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),('content',models.TextField()),('attachment',models.FileField(blank=True,null=True,upload_to='comment_attachments/')),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('author',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL)),('task',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='comments',to='tasks.task'))],options={'ordering':['created_at']}),
        migrations.CreateModel(name='AuditLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),('action',models.CharField(choices=[('created','Task Created'),('assigned','Task Assigned'),('status_changed','Status Changed'),('priority_changed','Priority Changed'),('commented','Comment Added'),('file_uploaded','File Uploaded'),('edited','Task Edited'),('deleted','Task Deleted')],max_length=30)),('detail',models.TextField(blank=True)),('timestamp',models.DateTimeField(auto_now_add=True)),('task',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='audit_logs',to='tasks.task')),('user',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL))],options={'ordering':['-timestamp']}),
        migrations.CreateModel(name='UserProfile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False)),('role',models.CharField(choices=[('admin','Admin'),('user','User')],default='user',max_length=10)),('department',models.CharField(blank=True,max_length=100)),('phone',models.CharField(blank=True,max_length=20)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to=settings.AUTH_USER_MODEL))],),
    ]
